apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemsapp-deployment
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: gemsapp-container=jozefcvik/jenkinsargocdgitops
    argocd-image-updater.argoproj.io/gemsapp-container.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gemsapp
  template:
    metadata:
      labels:
        app: gemsapp
    spec:
      containers:
      - name: gemsapp-container
        image: jozefcvik/jenkinsargocdgitops:latest
        ports:
        - containerPort: 3000  # change if your app runs on a different port
