apiVersion: v1
kind: Service
metadata:
  name: gemsapp-service
  namespace: gemsapp
spec:
  type: NodePort
  selector:
    app: gemsapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30036  # Optional: specify or let k8s assign
